const allFoods = [
    "Spaghetti Bolognese",
    "Caesar Salad",
    "Beef Wellington",
    "Clam Chowder",
    "Chicken Alfredo",
    "Shepherd's Pie",
    "Lobster Bisque",
    "Tandoori Chicken",
    "Shrimp Scampi",
    "New York Cheesecake",
    "Margherita Pizza",
    "Fish and Chips",
    "Hamburger",
    "French Onion Soup",
    "Lasagna",
    "Chicken Tikka Masala",
    "Fried Rice",
    "Sushi",
    "Pad Thai",
    "Ratatouille",
    "Eggs Benedict",
    "Mac and Cheese",
    "Falafel",
    "Goulash",
    "Moussaka",
    "Ramen",
    "Steak Frites",
    "Paella",
    "Peking Duck",
    "Quiche Lorraine",
    "Beef Stroganoff",
    "Tom Yum Soup",
    "Stuffed Peppers",
    "Carbonara",
    "Minestrone Soup",
    "Fajitas",
    "Tacos",
    "Barbecue Ribs",
    "Pho",
    "Dim Sum",
    "Baklava",
    "Tiramisu",
    "Crepes",
    "Chocolate Fondue",
    "Gelato",
    "Apple Pie",
    "Bangers and Mash",
    "Cobb Salad",
    "Croque Monsieur",
    "Burrito",
    "Chili Con Carne",
    "Huevos Rancheros",
    "Jambalaya",
    "Meatloaf",
    "Miso Soup",
    "Nicoise Salad",
    "Onigiri",
    "Pasta Primavera",
    "Pierogi",
    "Polenta",
    "Popcorn Shrimp",
    "Pot Roast",
    "Pumpkin Pie",
    "Red Beans and Rice",
    "Risotto",
    "Samosa",
    "Sauerbraten",
    "Scallops",
    "Shakshuka",
    "Shish Kebab",
    "Souffle",
    "Spanakopita",
    "Szechuan Chicken",
    "Tamales",
    "Tempura",
    "Teriyaki Chicken",
    "Tostadas",
    "Tuna Tartare",
    "Vichyssoise",
    "Waldorf Salad",
    "Wiener Schnitzel",
    "Yorkshire Pudding",
    "Ziti",
    "Zuppa Toscana"
];

export default allFoods;